version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - cmd: .\gradlew.bat build
#  - cmd: .\gradlew.bat assemble --no-daemon

test_script:
  - cmd: .\gradlew.bat check --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

artifacts:
  path: .\piil.jar
#  path: .\piil\bin\debug\piil.jar

environment:
  matrix:
    #- JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
  fast_finish: true

#deploy:
#  release: myproduct-v$(APPVEYOR_BUILD_VERSION)
#  description: 'Release description'
#  provider: GitHub
#  auth_token:
#    secure: <your encrypted token> # your encrypted token from GitHub
#  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
