version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - cmd: .\gradlew.bat assemble --no-daemon

test_script:
  - cmd: .\gradlew.bat check --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

matrix:
  fast_finish: true